// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxvojRjEj1MIIVg0M4CBltcHKYyY-zN_c',
    appId: '1:125426706541:web:fc774034d3edd367113764',
    messagingSenderId: '125426706541',
    projectId: 'blist-e9388',
    authDomain: 'blist-e9388.firebaseapp.com',
    storageBucket: 'blist-e9388.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqebmUspS7QY-uqqWNLycCD0LYXXkX3uw',
    appId: '1:125426706541:android:70a71594d93c11d9113764',
    messagingSenderId: '125426706541',
    projectId: 'blist-e9388',
    storageBucket: 'blist-e9388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIrbiEhrAybjt_nA--x2kFWWwkXlHKF_w',
    appId: '1:125426706541:ios:5754a10d84c1c092113764',
    messagingSenderId: '125426706541',
    projectId: 'blist-e9388',
    storageBucket: 'blist-e9388.firebasestorage.app',
    iosBundleId: 'com.example.kum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIrbiEhrAybjt_nA--x2kFWWwkXlHKF_w',
    appId: '1:125426706541:ios:5754a10d84c1c092113764',
    messagingSenderId: '125426706541',
    projectId: 'blist-e9388',
    storageBucket: 'blist-e9388.firebasestorage.app',
    iosBundleId: 'com.example.kum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxvojRjEj1MIIVg0M4CBltcHKYyY-zN_c',
    appId: '1:125426706541:web:f22c156146392711113764',
    messagingSenderId: '125426706541',
    projectId: 'blist-e9388',
    authDomain: 'blist-e9388.firebaseapp.com',
    storageBucket: 'blist-e9388.firebasestorage.app',
  );

}